### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by merelinguist** [kripod/next-starter-strict#1]
Hey there! Thank you for the amazing project. I've always struggled to make all the tools I want play well together! To that end, would you consider adding testing (perhaps with Jest) to the starter? I would be happy to submit a PR if you are interested in adding this but don't have the time to work on it yourself.

**Comment by kripod** [comment]
Hello,

Thank you for your feedback. Currently, I’m not planning to add tests, as the project isn’t meant to be opinionated about them and I would like to avoid bloat as much as possible. Please feel free to maintain a fork with tests included.

**Comment by merelinguist** [comment]
Okay, thanks!
